version: '3.3'
services:
  web:
    build: .docker
    restart: always
    ports:
      - "${HTTP_INTERFACE:-127.0.0.1}:${HTTP_PORT:-80}:80"
    volumes:
      - ./src:/var/www/html/
      - ./.env:/var/www/html/.env
      - ./.docker/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mariadb:10.5
    volumes:
       - './.docker/data/db:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
