version: '3.3'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        ports:
        - '${HTTP_INTERFACE:-127.0.0.1}:9000:80'
        links:
        - mysql:mysql
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        ports:
        - 1025:1025
        - 8025:8025
